### ISSUE TITLE
 I have no idea how to contact with you, so i leave a message here.

### ISSUE THREAD

**Issue by KurtBestor** [Stereoarts/FbxExtractMaterials#1]
I apologize, Stereoarts.
I have been study Unity in multiple environments, So I used to use the Github remote repository to synchronizing for main purpose.
I'd like to think it's OK to be public at that time, because i have the free Github plan, and there is no traffic on the repo.
But I accept this thought is wrong.
So I've change my Github plan, and make the repo as private.
By the way, your works are very brilliant! Thanks for share your nice works.
Sorry for uploading the works without permissions.

**Comment by Stereoarts** [comment]
Okay, I checked a that repository & that problem had been improved. (Changed to the private repository.)
Thanks to your resolving. Regards.
